[package]
name = "toml_parser"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
toml = "0.8.15"

[[example]]
name = "toml"
path = "examples/toml.rs"

[[example]]
name = "toml_test"
path = "examples/toml_test.rs"
