age = false
love = "axewbotx"
now = 12.12
wow = "12.12"
shit = 21
stuff = [1,2,3,4,5]
# [main]
# name = "axewbotx"
# shit = [false,true,false]
# false = true
# true = false
# 12.12.12.12.12.12 = false
# 13.13 = 13.13
# age = [{shit = 12.13, name = 13},2,3]
# power = {name = 12.12,age = 12.13,14.14 = 12.12}
# now_shit = [
# 	{name = 12.12},
# 	{13.13.13 = 12},
# 	{false = false},
# 	{false = true},
# 	{name = [1.2,3.4,1412123.3,12314]},
# 	{true = [false,true,false]}
# ]
# main = false
#
# [12.13.13]
# name = "user"
