age = false
power = {name = 12.12,age = 12.13,helo = 12.12}
some_shit = "some_name"
now = 12.12
shit = 21
wow = [[1,2],["shit","hello"]]
stuff = [1,false,"Shit","Wow",5.12312]

["hello"]
name = "axewbotx"
shit = [false,true,false]
false = true
true = false
age = [{shit = 12.13, name = 13},2,3]
power = {name = 12.12,age = 12.13,14 = 12.12}
now_shit = [
	{name = 12.12},
	{13 = 12},
	{false = false},
	{false = true},
	{name = [1.2,3.4,1412123.3,12314]},
	{true = [false,true,false]}
]
main = false

[hellyeah]
some_si = false
